### ISSUE TITLE
Group form fields in columns

### ISSUE THREAD

**Issue by newtec-foggia** [Formfeed-UK/nova-theming-classes#1]
sorry, it is not clear to me, in the resource I have more fields, once the package is installed how do I proceed?

thanks,

**Comment by ianrobertsFF** [comment]
The package only adds css classes to the Nova and 3rd party package vue components.

In order to achieve any specific functionality as a result you need to write css that targets those components. 

For example you could do something like:

```css
.resource-{your resource}.component-form-panel > .component-card {
    display:grid;
    grid-template-columns: 50% 50%;
}
```

You can inspect the html of the page to see specifically what css classes you are working with, but they follow the pattern described in the docs.
